SELECT A.AUTHOR_ID, A.AUTHOR_NAME, I.CATEGORY, SUM(I.TOTAL)
FROM (SELECT B.AUTHOR_ID AS AUTHOR_ID, CATEGORY, B.PRICE*S.SALES AS TOTAL 
        FROM (SELECT BOOK_ID, SUM(SALES) AS SALES
            FROM BOOK_SALES
            WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
            GROUP BY BOOK_ID) S 
            JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID) I 
    JOIN AUTHOR A ON I.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, I.CATEGORY
ORDER BY A.AUTHOR_ID ASC, I.CATEGORY DESC