SELECT C.ID
FROM ECOLI_DATA C
WHERE C.PARENT_ID IN (
    SELECT P.ID
    FROM ECOLI_DATA P
    WHERE P.PARENT_ID IN (
        SELECT G.ID
        FROM ECOLI_DATA G
        WHERE G.PARENT_ID IS NULL
    )
)
ORDER BY ID ASC;