SELECT E.ID, CASE WHEN C.CHILD_COUNT IS NULL THEN 0 ELSE C.CHILD_COUNT END AS CHILD_COUNT
FROM (
    SELECT COUNT(PARENT_ID) AS CHILD_COUNT, PARENT_ID
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) AS C RIGHT OUTER JOIN ECOLI_DATA E ON C.PARENT_ID = E.ID
ORDER BY E.ID ASC;