SELECT P.PRODUCT_CODE, (PRICE*SALE.AMOUNT) AS SALES
FROM (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
     FROM OFFLINE_SALE
     GROUP BY PRODUCT_ID
     ) AS SALE JOIN PRODUCT P ON SALE.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC