SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, 
    N.PRODUCT_ID, 
    N.USER_ID,
    N.SALES_AMOUNT
FROM ONLINE_SALE N
WHERE SALES_DATE BETWEEN TO_DATE('2022-03-01', 'YYYY-MM-DD') AND TO_DATE('2022-03-31', 'YYYY-MM-DD')
UNION ALL
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, 
    F.PRODUCT_ID, 
    NULL, 
    F.SALES_AMOUNT
FROM OFFLINE_SALE F 
WHERE SALES_DATE BETWEEN TO_DATE('2022-03-01', 'YYYY-MM-DD') AND TO_DATE('2022-03-31', 'YYYY-MM-DD')
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC