SELECT ID, NAME
FROM (
    SELECT (O.DATETIME - I.DATETIME) AS DAT, I.ANIMAL_ID AS ID, I.NAME AS NAME
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY DAT DESC
)
WHERE ROWNUM < 3