SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES AS FAVORITES
FROM REST_INFO I
WHERE (I.FOOD_TYPE, I.FAVORITES) IN (SELECT I2.FOOD_TYPE, MAX(I2.FAVORITES)
                                    FROM REST_INFO I2
                                    GROUP BY I2.FOOD_TYPE)
ORDER BY I.FOOD_TYPE DESC