SELECT I2.REST_ID, I2.REST_NAME, I2.FOOD_TYPE, I2.FAVORITES, I2.ADDRESS, R2.SCORE
FROM 
(
    SELECT R.REST_ID, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW R JOIN REST_INFO I ON R.REST_ID = I.REST_ID 
    WHERE I.ADDRESS LIKE '서울%'
    GROUP BY R.REST_ID
) R2 JOIN REST_INFO I2 ON R2.REST_ID = I2.REST_ID 
ORDER BY R2.SCORE DESC, I2.FAVORITES DESC