SELECT
    H.CAR_ID,
    CASE
    WHEN H.CAR_ID IN (SELECT H2.CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
                        WHERE TO_DATE('2022-10-16', 'YYYY-MM-DD') BETWEEN H2.START_DATE AND H2.END_DATE)
                        THEN '대여중'
    ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC