SELECT NAME, T
FROM (SELECT (SYSDATE - I.DATETIME) AS DAT, I.NAME AS NAME, I.DATETIME AS T
    FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.DATETIME IS NULL
    ORDER BY DAT DESC)
WHERE ROWNUM < 4
ORDER BY T ASC