SELECT FLAVOR
FROM (
    SELECT F.FLAVOR AS FLAVOR, F.TOTAL_ORDER + J.TOTAL_ORDER AS COUNT
    FROM  
        (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR) J JOIN FIRST_HALF F ON F.FLAVOR = J.FLAVOR
    ORDER BY COUNT DESC)
WHERE ROWNUM <= 3