SELECT E.APNT_NO, E.PT_NAME, E.PT_NO, E.MCDP_CD, D.DR_NAME, E.APNT_YMD
FROM
(
    SELECT A.APNT_NO AS APNT_NO, 
            P.PT_NAME AS PT_NAME, 
            P.PT_NO AS PT_NO, 
            A.MCDP_CD AS MCDP_CD, 
            A.APNT_YMD AS APNT_YMD, 
            A.MDDR_ID AS MDDR_ID
    FROM PATIENT P JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO
    WHERE TO_CHAR(A.APNT_YMD, 'YYYYMMDD') = '20220413'
    AND A.APNT_CNCL_YN = 'N'
) E JOIN DOCTOR D ON E.MDDR_ID = D.DR_ID
ORDER BY E.APNT_YMD ASC