SELECT DISTINCT(D.ID), D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM (
    SELECT CODE AS SKILL_CODE 
    FROM SKILLCODES
    WHERE CATEGORY LIKE "Front End"
) AS S INNER JOIN DEVELOPERS D ON (S.SKILL_CODE & D.SKILL_CODE) > 0
ORDER BY D.ID ASC;