SELECT MEMBER_ID, MEMBER_NAME, GENDER, date_format(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' and date_format(DATE_OF_BIRTH, '%m') = '03' and TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;