SELECT P.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD')
FROM REST_REVIEW R JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM 
        (SELECT MEMBER_ID,
                COUNT(*) AS CNT,
                ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) AS RNK
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        )
    WHERE RNK = 1
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC