SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A
 JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME > B.DATETIME
ORDER BY A.DATETIME ASC


-- ANIMAL_INS의 DATETIME 보다 ANIMAL_OUTS의 DATETIME이 더 빠른 동물의 아이디와 이름 조회