SELECT EXTRACT(MONTH FROM C.START_DATE) AS MONTH, 
        C.CAR_ID AS CAR_ID, 
        COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C 
WHERE C.CAR_ID IN (SELECT C3.CAR_ID 
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C3
                    WHERE C3.START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') 
                                            AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
                    GROUP BY C3.CAR_ID
                    HAVING COUNT(*) >= 5)
  AND C.START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') 
                        AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
GROUP BY EXTRACT(MONTH FROM C.START_DATE), C.CAR_ID
ORDER BY MONTH ASC, C.CAR_ID DESC