SELECT E.YEAR AS YEAR, (E.MAX_SIZE - D.SIZE_OF_COLONY) AS YEAR_DEV, D.ID
FROM (
    SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) E JOIN ECOLI_DATA D ON E.YEAR = YEAR(D.DIFFERENTIATION_DATE)
ORDER BY E.YEAR ASC, YEAR_DEV ASC;