SELECT S.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL 
FROM 
(SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE
WHERE YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
) S JOIN HR_EMPLOYEES E ON S.EMP_NO = E.EMP_NO
LIMIT 1