SELECT '/home/grep/src/' || b.BOARD_ID || '/' || f.FILE_ID || f.FILE_NAME || f.FILE_EXT as FILE_PATH
FROM USED_GOODS_BOARD b JOIN USED_GOODS_FILE f ON b.BOARD_ID = f.BOARD_ID
WHERE b.VIEWS = (SELECT MAX(b2.VIEWS) FROM USED_GOODS_BOARD b2)
ORDER BY f.FILE_ID DESC