SELECT P2.CATEGORY, P2.PRICE, P2.PRODUCT_NAME
FROM FOOD_PRODUCT P2
WHERE
(P2.CATEGORY, P2.PRICE) IN
    (SELECT P1.CATEGORY, MAX(P1.PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT P1
    GROUP BY P1.CATEGORY)
AND P2.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY P2.PRICE DESC