SELECT 
CASE WHEN (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE CATEGORY LIKE "%Front%"
) & D.SKILL_CODE > 0 AND
    (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME LIKE "Python"
) & D.SKILL_CODE > 0
THEN "A"
WHEN (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE NAME IN ("C#")
) & D.SKILL_CODE > 0 THEN "B"
WHEN (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE CATEGORY LIKE "%Front%"
) & D.SKILL_CODE > 0 THEN "C"
END AS "GRADE",
ID,
EMAIL
FROM DEVELOPERS D
WHERE CASE WHEN (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE CATEGORY LIKE "%Front%"
) & D.SKILL_CODE > 0 AND
    (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME LIKE "Python"
) & D.SKILL_CODE > 0
THEN "A"
WHEN (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE NAME IN ("C#")
) & D.SKILL_CODE > 0 THEN "B"
WHEN (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE CATEGORY LIKE "%Front%"
) & D.SKILL_CODE > 0 THEN "C"
END IS NOT NULL
ORDER BY GRADE ASC, ID ASC;

